[main]
# Police
font=Cousine:size=11

include=/home/thanbv/.config/foot/themes/github_dark_dimmed

[url]
osc8-underline=always

#[cursor]
#style=block
#blink=yes

[mouse]
hide-when-typing=yes

#[key-bindings]
#scrollback-up-page=Control+Shift+Page_Up
#scrollback-down-page=Control+Shift+Page_Down
#scrollback-up-line=Control+Shift+Up
#scrollback-down-line=Control+Shift+Down
